version: '2.1'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-monitoring-app:
    image: com.rbiedrawa/kafka-monitoring:0.0.1-SNAPSHOT
    container_name: kafka-monitoring-app
    restart: always
    depends_on:
      - kafka
    ports:
      - 7777:7777
    environment:
      spring.profiles.active: docker
      spring.kafka.bootstrap-servers: "kafka:29092"

  prometheus:
    image: prom/prometheus:v2.26.0
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9090" ]
      start_period: 10s
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:7.5.2
    container_name: grafana
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "3000" ]
      start_period: 10s
    ports:
      - 3000:3000
    environment:
      #      - "GF_INSTALL_PLUGINS=grafana-piechart-panel"
      - "GF_USERS_ALLOW_SIGN_UP=false"
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=password"
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  kafka-minion:
    image: quay.io/cloudhut/kminion:v2.1.0
    hostname: kafka-minion
    container_name: kafka-minion
    depends_on:
      - kafka
    ports:
      - 8080:8080
    environment:
      KAFKA_BROKERS: kafka:29092
      CONFIG_FILEPATH: /etc/kminion/config.yaml
    restart: unless-stopped
    volumes:
      - ./config/kminion/config.yaml:/etc/kminion/config.yaml